name: tdlogistic_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+23

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: 
  google_maps_flutter: 2.1.12
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  flutter_webrtc: ^0.11.7
  web_socket_channel: ^3.0.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  socket_io_client: ^3.0.0
  archive: ^3.6.1
  permission_handler: ^11.3.1
  mime: ^2.0.0
  dio: ^5.7.0
  http_parser: ^4.0.2
  path_provider: ^2.1.4
  dvhcvn: ^2.0.20240901
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.1
  signature: ^5.5.0
  flutter_launcher_icons: ^0.14.3
  geolocator: ^13.0.1
  share_plus: ^10.1.1
  flutter_native_contact_picker: ^0.0.9
  flutter_background_service: ^5.0.10
  qr_flutter: ^4.1.0
  flutter_contacts: ^1.1.9+2
  easy_localization: ^3.0.7
  intl: ^0.19.0 
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/done.png
    - lib/assets/
    - lib/assets/translations/
