// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNLzS6kLumU5AFHH0mjvufRq5XNx7ZXs',
    appId: '1:549484205620:web:e5e0153c7a6be79eb41c61',
    messagingSenderId: '549484205620',
    projectId: 'tdlogistics-f7d63',
    authDomain: 'tdlogistics-f7d63.firebaseapp.com',
    storageBucket: 'tdlogistics-f7d63.appspot.com',
    measurementId: 'G-Z70VKTGH49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ-xhPi5Q9SKvOWJhECst1K7nwyvKo_ag',
    appId: '1:549484205620:android:28fa068de2864eb2b41c61',
    messagingSenderId: '549484205620',
    projectId: 'tdlogistics-f7d63',
    storageBucket: 'tdlogistics-f7d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCCieQ1uJiVFOcAe6Dl9DOeD8PT0z5Qs',
    appId: '1:549484205620:ios:8f280473d53327dcb41c61',
    messagingSenderId: '549484205620',
    projectId: 'tdlogistics-f7d63',
    storageBucket: 'tdlogistics-f7d63.appspot.com',
    iosBundleId: 'com.example.tdlogisticV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuCCieQ1uJiVFOcAe6Dl9DOeD8PT0z5Qs',
    appId: '1:549484205620:ios:8f280473d53327dcb41c61',
    messagingSenderId: '549484205620',
    projectId: 'tdlogistics-f7d63',
    storageBucket: 'tdlogistics-f7d63.appspot.com',
    iosBundleId: 'com.example.tdlogisticV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgNLzS6kLumU5AFHH0mjvufRq5XNx7ZXs',
    appId: '1:549484205620:web:3cd27796b23efb71b41c61',
    messagingSenderId: '549484205620',
    projectId: 'tdlogistics-f7d63',
    authDomain: 'tdlogistics-f7d63.firebaseapp.com',
    storageBucket: 'tdlogistics-f7d63.appspot.com',
    measurementId: 'G-FTZ3LHTB25',
  );
}
